//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emplist
    {
        public string Ename { get; set; }
        public Nullable<int> Eid { get; set; }
        public string Addresh { get; set; }
        public Nullable<int> MobileNumber { get; set; }
    }
}
